language: python
dist: trusty
sudo: required

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

services:
  - mongodb

python:
  - "3.6"

git:
  depth: false

install:
  # command in shell script need sudo
  - sudo apt-get update
  - source build/build.sh

before_script:
  # configure mongo unit test database
  - mongo UnitTest --eval 'db.createUser({user:"unit", pwd:"UnitTest-7g6sSDgRgs", roles:[{role:"readWrite", db:"UnitTest"}]});'
  # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # need give xvfb some time to start

script:
  - packages="conffor, database, logsetting, netgraph, twitter"
  - python -m nose -w . -vs --with-coverage --cover-package="$packages"

after_success:
  coveralls

notifications:
  email: true
