language: python
dist: trusty
sudo: required

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.6-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools

services:
  - mongodb

python:
  - "3.6"

git:
  depth: false

install:
  # command in shell script need sudo
  - source build/build.sh
  # configure mongo unit test database
  - mongo config/init-db.js

before_script:
  # configure a headless display to test plot generation
  # need give xvfb some time to start
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - flake8 .

script:
  - py.test --cov=lib test/

after_success:
  coveralls

notifications:
  email: true
