language: python
dist: trusty
sudo: required

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

services:
  - mongodb

python:
  - "3.5"

before_install:
  # command in shell script need sudo
  - source travis_env_init.sh

install:
  - pip install -r requirements.txt --timeout 600

before_script:
  # configure mongo unit test database
  - mongo UnitTest --eval 'db.createUser({user:"unit", pwd:"UnitTest", roles:["readWrite"]});'
  # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # need give xvfb some time to start

script:
  - packages="conffor, database, logsetting, netgraph, twitter"
  - python -m nose -w . -vs --with-coverage --cover-package="$packages"

after_success:
  coveralls

notifications:
  email: true
